title: Linear Programming Chapter
author: Ghaith Rabadi
execute:
  execute_notebooks: auto  # Run notebooks only if they have unexecuted cells
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
