title: Linear Programming Chapter
author: Ghaith Rabadi
copyright: "2025"
execute:
  execute_notebooks: force
html:
  use_repository_button: false
  use_issues_button: false
  use_edit_page_button: false
launch_buttons:
  binderhub_url: https://mybinder.org
  thebe: true
interactive:
  kernel_name: python3
  use_thebe: true
repository:
  url: https://github.com/MohammadBaniAbdElNabi/Linear-programming  
  branch: main  